### PR TITLE
respect this.options.gulp option in gulp generator

### LINKED ISSUE #189: should check this.options.gulp
https://github.com/yeoman/generator-node/blob/master/generators/gulp/index.js#L71

Gulp generator runs even if `gulp: false`

### PR DESCRIPTION
**Pull request by tjwebb**
- resolves #189

### CODE REVIEW

**Comment by hemanth** [comment]
:+1:

**Comment by SBoudrias** [comment]
Wait a minute, there's no `gulp` options.

**Comment by hemanth** [comment]
Oh #189 puzzled me as well!
[L10-L35](https://github.com/yeoman/generator-node/blob/master/generators/gulp/index.js#L10-L35) has no options, it's should be optional is in't? 

My bad, @SBoudrias Shall we revert this or add an option for gulp? Just the boilerplate without gulp doesn't make sense, rather we would need a option between gulp and npm-scripts.

**Comment by tjwebb** [comment]
From README:
> gulp (Boolean, default true) include or not a gulpfile.

There is most certainly a gulp option. Setting it to false, disables the gulp generation, as one would expect.

**Comment by SBoudrias** [comment]
This was an error on the documentation.

I just added the option in a follow up commit, so we're good.

**Comment by tjwebb** [comment]
Ok cool

**Comment by hemanth** [comment]
@tjwebb You shall be adding the options? Thanks. (Sorry about the confusion)

**Comment by hemanth** [comment]
Ah, not to worry, @SBoudrias  has already done [that](https://github.com/yeoman/generator-node/commit/9b6fd696c4b5959f2d4e7c97947c57988466f188).

**Pull request merged**
