### PR TITLE
Update to babel 6

### PR DESCRIPTION
**Pull request by SBoudrias**
Not sure why but the test task with this new output gulpfile is currently broken. It's kinda late now, and I don't know when I'll have time to finish wrapping this, so feel free to pull this branch and send a PR to make this work!

### CODE REVIEW

**Comment by hemanth** [comment]
@SBoudrias Is there a todo list in your mind?

**Comment by SBoudrias** [comment]
@hemanth nope, feel free to take the branch and make it work 😝 

As a repo contributor, you can add commits and push over my branch.

**Comment by hemanth** [comment]
@SBoudrias heh heh cool ;)

**Comment by SBoudrias** [comment]
Someone else sent a working PR. Dropping this one.

**Pull request closed without merging**
