### PR TITLE
CLI: adding `.gitignore` for `node_modules` folder

### PR DESCRIPTION
**Pull request by EvanLovely**
Seems like a very sensible addition!

### CODE REVIEW

**Comment by SBoudrias** [comment]
This is done by https://github.com/yeoman/generator-node/blob/master/generators/git/index.js

Did you ran into an issue?

**Comment by EvanLovely** [comment]
Yes I did; when I run `yo node:cli` I get only two files created: 

- `package.json`
- `lib/cli.js`

**Comment by SBoudrias** [comment]
Oh yes, that's correct. `node:cli` only add to a current project. It doesn't generate a new project.

What you want is `yo node --cli`

**Comment by EvanLovely** [comment]
Thanks!

**Pull request closed without merging**
