### PR TITLE
Add CLI boilerplate

### PR DESCRIPTION
**Pull request by arthurvr**
Implements a CLI boilerplate to fix https://github.com/yeoman/generator-node/issues/112

I noticed some other issues with the build system on the while. I'll open issues about it but that shouldn't block this.

Fix #122

### CODE REVIEW

**Comment by stevemao** [comment]
Missing the docs?

**Comment by arthurvr** [comment]
@stevemao Done. Not much to document about this, though.

**Comment by stevemao** [comment]
Thanks :)

**Comment by hemanth** [comment]
Thanks @arthurvr :+1:

**Pull request merged**
