### PR TITLE
throw err

### PR DESCRIPTION
**Pull request by calidion**
enabled error prompt and throw error on occurring

### CODE REVIEW

**Comment by SBoudrias** [comment]
I don't see how's that fixing the issue. We don't want to throw, we want to run all test and then only fails. See the `.on('end')` callback.

**Comment by calidion** [comment]
@SBoudrias currently there is no clue how it fails. so it would be better to stop the progress when it fails.
when it succeeds no need to throw.
if it encounters errors, no need to continue.

**Comment by calidion** [comment]
there is noting more need to be done, but let users know why gulp tasks can't continue.

**Comment by calidion** [comment]
seems i am not full understand.

**Comment by calidion** [comment]
the `end` event won't be called when errors occur,
so the idea of keeping all the tasks done is not realistic.
because the tasks are chainable only when they are correctly executed.

**Comment by calidion** [comment]
@SBoudrias please consider merge  this pull request and close my three issues.

**Comment by SBoudrias** [comment]
I'm sorry, but this is not the correct fix. It fixes your issue, but it's breaking the expected workflow of Gulp; and by this will create new issues.

We want to fix the issue you're having, but that's not the right solution.

I'm closing this PR, but I'll leave the issue open.

**Comment by calidion** [comment]
what is the expected workflow?
although gulp works on streams, it still breaks when errors occur.
why should not this project?
I don't know what you means here by expected workflow.

**Pull request closed without merging**
