### PR TITLE
Allow the generator to be used behind a proxy

### LINKED ISSUE #274: Usage behind proxy
To allow the generator (and all other generators that depend on it) to be used behind a proxy we could add   [caw](https://www.npmjs.com/package/caw) to the request made by `github-username`.

`github-username` doesn't currently support the `agent` property of the [`http-request` options](https://nodejs.org/api/http.html#http_http_request_options_callback) but I've made a [PR](https://github.com/sindresorhus/github-username/pull/8) to achieve this.

There might other modules that need `caw` but this is at least a starting point.

### PR DESCRIPTION
**Pull request by MarcoScabbiolo**
Included [global-tunnel-ng](https://github.com/np-maintain/global-tunnel) that overrides Node's [ Agent](https://nodejs.org/api/http.html#http_class_http_agent) with an Agent capable of tunneling through a proxy. Because `global-tunnel` is initialized with no parameters, the Agent will be overwritten only if a proxy is configured in the widely used environment variables `http_proxy` and `https_proxy`, so this should have no effect for users who are not explicitly using a proxy.

The most common use case is to set these variables at a `.bashrc` or `.zshrc` file, to have them on every shell session

```bash
export http_proxy="http://www.proxy.com"
```

Fixes #274

### CODE REVIEW

**Comment by SBoudrias** [comment]
Hey @MarcoScabbiolo thanks for your PR. Could you take a few minutes to explain why and how that works?

**Comment by SBoudrias** [comment]
Also it looks like the project is deprecated and has move to https://github.com/np-maintain/global-tunnel

**Comment by MarcoScabbiolo** [comment]
@SBoudrias My bad, should have seen that, I've switched to the "maintained" version but it fails in Node 4, I'll be digging into that this weekend. Also I added an explanation of why and how this works.

**Comment by SBoudrias** [comment]
@sindresorhus @mischah do you guys think we should include this in `yo` directly instead?

I think Sindre has touched proxies a bit with `got` - but that turned out to be fairly complicated right?

**Comment by sindresorhus** [comment]
> I think Sindre has touched proxies a bit with got - but that turned out to be fairly complicated right?

It's an absolute mess.

**Comment by mischah** [comment]
> do you guys think we should include this in yo directly instead?
Jop. I think having that in `yo` would be nice for generator user and authors. They just don’t have to care.

But I don’t know how well this is maintained 🤔 
image

The [PR](https://github.com/np-maintain/global-tunnel/pull/10) from @MarcoScabbiolo is still not merged.

**Comment by MarcoScabbiolo** [comment]
I couldn't replicate the build error using node 4 with nvm and `npm test` or `yarn test`, I have no clue why the Travis build is failing.

About `global-tunnel`, it isn't well maintained but it is working, an option is to make a fork and a new npm package but it doesn't have the right license to do that and I don't like the idea anyway. I'll keep trying to get my PR merged and help maintain the repo because it is really useful to me.

It would be great to have this included in `yo`, I think it will help a lot users/owners, many don't get to choose whether to use a proxy or not.

**Comment by SBoudrias** [comment]
@MarcoScabbiolo please do send a PR to yo.

A lot of users have been having a lot of proxy issues, and I'm willing to try this out seeing if it might help!

**Pull request closed without merging**
