### PR TITLE
fix mismatched var names between app and readme

### PR DESCRIPTION
**Pull request by stevemao**
In app/index.js, its `githubUsername` but in readme/index.js its `githubAccount`.
In app/index.js, its `authorUrl` but in readme/index.js its `authorURL`.
So the generated readme.md has parts missing.
Test is also added.

### CODE REVIEW

**Comment by stevemao** [comment]
Ref: https://github.com/stevemao/conventional-commits-filter/commit/99f0b5ed06315ab38610923d00713c4f68fafac7

**Comment by SBoudrias** [comment]
Awesome, thanks!

**Comment by stevemao** [comment]
Thanks. Can we make a patch release? I think we've fixed quite a few things since last release.

**Comment by stevemao** [comment]
Should be minor because `cli` is added.

**Pull request merged**
