### PR TITLE
Enhance author field handling

### PR DESCRIPTION
**Pull request by dasilvacontin**
The comment about not handling author field when it's a string no longer applies.

I also joined the type checks into a single if/else.

### CODE REVIEW

**Comment by SBoudrias** [comment]
Can you squash your commits?

We'll merge afterwards.

**Comment by dasilvacontin** [comment]
Done!

**Comment by SBoudrias** [comment]
Awesome, thanks a lot!

**Comment by dasilvacontin** [comment]
No problemo! :)

**Pull request merged**
