### PR TITLE
downgrading husky 2.6.0 and add eslintrc.js

### PR DESCRIPTION
**Pull request by bung87**
https://github.com/typicode/husky/blob/master/src/installer/gitRevParse.ts#L9
https://github.com/typicode/husky/issues/580

add eslintrc.js so the brand new package can pass `npm run test`

### CODE REVIEW

**Comment by SBoudrias** [comment]
Can you explain what Husky 3.x is breaking on your side? It's unclear to me what's the issue from the issue you linked. Husky 3 has been working fine where I've used it.

**Comment by bung87** [comment]
during post install husky ,when `Setting up git hooks` it will throw error , I'v tried multiple times.

**Comment by glensc** [comment]
you should create pull request per each feature.

- husky change: questionable
- eslint: probably would had been already merged if it wasn't combined with husky

**Comment by glensc** [comment]
also, https://github.com/typicode/husky/issues/580 is closed by now

**Pull request closed without merging**
