### PR TITLE
Replace deprecated prepublish by prepublishOnly

### PR DESCRIPTION
**Pull request by AlekseyLeshko**
[Prepublish is deprecated](https://docs.npmjs.com/misc/scripts#deprecation-note) and time for prepare

### CODE REVIEW

**Comment by AlekseyLeshko** [comment]
Yep, you are right!
We should use `prepublishOnly` it is only run when call `npm publish`.
I will fix it.

**Comment by SBoudrias** [comment]
Which version of npm do we require for this to work? I feel like we should let the user know if they're on an old version that won't work.

**Comment by mischah** [comment]
> Which version of npm do we require for this to work? 
It came with `npm@4.0.0`

Where do you want to communicate that beside the changelog? Add an info to the README?

**Comment by AlekseyLeshko** [comment]
I hope the most developers use last version npm, but I understand not all.
May be included warning block in generating process?
Check npm version and write message to wish for update npm.

**Comment by SBoudrias** [comment]
Sorry for not answering sooner.

I think we could add `npm > 4` to the `engine` field of `package.json` for good measure. Then we'll be good to merge I think.

**Comment by AlekseyLeshko** [comment]
[`Engines` block don't work without `engine-strict` config tag.](https://github.com/npm/npm/issues/17778)([docs engines]( https://docs.npmjs.com/files/package.json#engines))
Should write warning message, but without `--engine-strict` tag doesn't.
[npm test for `npm test with --engine-strict`](https://github.com/npm/npm/blob/d46015256941ddfff1463338e3e2f8f77624a1ff/test/tap/check-engine-reqs.js#L31)

Set `engine-strict` in package as default or add custom warning?

**Comment by SBoudrias** [comment]
I think it's fine to allow npm show the default warning. I don't think we need to spend too much efforts on this, worse case, the nsp check will be skipped for users on old npm release.

**Comment by SBoudrias** [comment]
Thanks a lot for the PR!

**Pull request merged**
